- hosts: do
  remote_user: root
  sudo: yes
  vars:
    use_datadog: true
  roles:
     - { role: datadog, dd_api_key: '', when: use_datadog }
     - { role: nginx, use_datadog: use_datadog }
     - { role: nodejs }
     - { role: mongodb, use_datadog: use_datadog }
